#' Over-sample (Multiply/Duplicate) specific cells in a Seurat object.
#'
#' This function creates a new Seurat object by duplicating the count data and
#' metadata for cells that match both a specified condition and a set of target
#' cell types. This is useful for simulating a shift in cell type composition or
#' for over-sampling rare cell populations within a specific biological
#' condition.
#'
#' The function only duplicates cells; it does not perform any normalization,
#' scaling, or dimensional reduction on the new object. New cell names are
#' generated by appending a suffix (e.g., "_1", "_2", ...) to the original cell
#' barcodes.
#'
#' @param seurat_object The Seurat object to modify.
#' @param condition_column A character string specifying the name of the
#'   metadata column that contains the primary condition (e.g., \code{"group"},
#'   \code{"treatment"}).
#' @param target_condition A character string specifying the exact value within
#'   \code{condition_column} that identifies the cells to be targeted for
#'   duplication (e.g., \code{"disease"}, \code{"treated"}).
#' @param celltype_column A character string specifying the name of the metadata
#'   column that contains the cell type annotation (e.g.,
#'   \code{"seurat_clusters"}, \code{"cell_type_l2"}).
#' @param target_celltypes A character vector of specific cell type annotations
#'   within \code{celltype_column} to be targeted (e.g., \code{c("CD8 T",
#'   "NK")}).
#' @param multiplier An integer specifying the factor by which to multiply
#'   (duplicate) the selected cells. A value of \code{2} results in one copy
#'   being added (doubling the count), a value of \code{3} results in two
#'   copies, and so on. Must be \code{1} or greater. If \code{1}, the original
#'   object is returned.
#'
#' @return A new \code{Seurat} object containing the original cells plus
#'   (\code{multiplier} - 1) copies of the targeted cells.
#'
#' @export seurat_multiply_cells_in_condition
#'
#' @examples
#' \donttest{
#' # ---------------------------------------------------------------------
#' # Example: Simulating differential cell abundance using the function
#' # ---------------------------------------------------------------------
#'
#' # 1. Install and load necessary data (requires the SeuratData package)
#' # Note: SeuratData needs to be installed, but it is not a direct dependency
#' # of your current function, so it's placed in the example.
#' library(SeuratData)
#' # InstallData("pbmc3k") # Uncomment to install the dataset if necessary
#' data("pbmc3k")
#'
#' # Ensure the object is updated to the latest Seurat standard
#' pbmc3k <- Seurat::UpdateSeuratObject(pbmc3k)
#' head(pbmc3k@meta.data)
#'
#' # 2. Prepare the object: Create dummy 'sample_id' and 'condition_id' metadata
#' n_samples <- 40
#' n_groups <- 2
#'
#' pbmc3k$sample_id <- ""
#' }
#' pbmc3k$sample_id <- rep(
#'   x = paste0("sample", seq(n_samples)),
#'   length.out = length(pbmc3k$sample_id)
#' )
#' pbmc3k$condition_id <- ""
#' pbmc3k$condition_id <- c(
#'   rep("condition1", n_samples / n_groups),
#'   rep("condition2", n_samples / n_groups)
#' )
#'
#' # 3. Apply the function
#' # To multiply "CD8 T" cells AND "NK" cells
#' # ONLY within "condition2" by a factor of 5:
#' pbmc3k_DiffAbu <- seurat_multiply_cells_in_condition(
#'   seurat_object = pbmc3k,
#'   condition_column = "condition_id",
#'   target_condition = "condition2",
#'   celltype_column = "seurat_annotations", # Cell type annotation column
#'   target_celltypes = c("CD8 T", "NK"),
#'   multiplier = 5
#' )
#'
#' # 4. Verification (Optional):
#' # Check the cell counts before the multiplication
#' # (uses original 'condition' column)
#' table(pbmc3k@meta.data$condition, pbmc3k@meta.data$seurat_annotation)
#' # Check the cell counts after (uses the newly created 'condition_id' column)
#' table(
#'   pbmc3k_DiffAbu@meta.data$condition_id,
#'   pbmc3k_DiffAbu@meta.data$seurat_annotations
#' )
#'
seurat_multiply_cells_in_condition <- function(
  seurat_object,
  condition_column,
  target_condition,
  celltype_column,
  target_celltypes,
  multiplier
) {
  if (!requireNamespace("Seurat", quietly = TRUE)) {
    stop(
      "Package \"Seurat\" must be installed to use this function.",
      call. = FALSE
    )
  }

  if (multiplier < 1) {
    stop("Multiplier must be 1 or greater.")
  }

  # --- Input Validation ---
  if (!(condition_column %in% names(seurat_object@meta.data))) {
    stop(
      "Condition column '",
      condition_column,
      "' not found in Seurat metadata."
    )
  }
  if (!(celltype_column %in% names(seurat_object@meta.data))) {
    stop(
      "Cell type column '",
      celltype_column,
      "' not found in Seurat metadata."
    )
  }

  # 1. Identify the cells to be duplicated (Logical AND)
  original_cell_names <- rownames(seurat_object@meta.data)
  metadata <- seurat_object@meta.data

  # Logical vector 1: Cells matching the target condition
  condition_logic <- metadata[[condition_column]] == target_condition

  # Logical vector 2: Cells matching ANY of the target cell types
  celltype_logic <- metadata[[celltype_column]] %in% target_celltypes

  # Final selection: Cells that satisfy BOTH criteria (logical AND: &)
  cells_to_copy_logic <- condition_logic & celltype_logic
  cells_to_copy_names <- original_cell_names[cells_to_copy_logic]


  if (length(cells_to_copy_names) == 0) {
    warning(
      "No cells found matching both '", target_condition,
      "' and any of the specified cell types."
    )
    return(seurat_object)
  }

  # Initial data to start the accumulation
  multiplied_counts <- seurat_object@assays[["RNA"]]$counts
  multiplied_metadata <- metadata

  # 2. Iterate and Duplicate (Multiplier - 1) times
  # We subset the original data once
  # to ensure we don't accidentally subset the growing multiplied data
  original_counts_to_copy <- multiplied_counts[, cells_to_copy_names]
  original_metadata_to_copy <- multiplied_metadata[cells_to_copy_names, ]

  for (i in seq_len(multiplier - 1)) {
    suffix <- paste0("_", i)

    # --- Counts Duplication ---
    new_cell_names_counts <- paste0(cells_to_copy_names, suffix)
    counts_to_copy <- original_counts_to_copy
    colnames(counts_to_copy) <- new_cell_names_counts

    multiplied_counts <- cbind(multiplied_counts, counts_to_copy)

    # --- Metadata Duplication ---
    new_cell_names_meta <- paste0(rownames(original_metadata_to_copy), suffix)
    metadata_to_copy <- original_metadata_to_copy
    rownames(metadata_to_copy) <- new_cell_names_meta

    multiplied_metadata <- rbind(multiplied_metadata, metadata_to_copy)
  }

  # 3. Create the new Seurat Object
  new_seurat_object <- Seurat::CreateSeuratObject(
    counts = multiplied_counts,
    meta.data = multiplied_metadata,
    assay = "RNA"
  )

  new_seurat_object@project.name <- paste0(
    seurat_object@project.name,
    "_Targeted_Multiplied"
  )

  return(new_seurat_object)
}
